dtype: float32
output_dir: ./outputs
log_level: INFO

task:
  name: ornstein_uhlenbeck
  n_tasks: 0
  n_data: 0
  n_dims: 2
  n_points: 64
  n_max_points: 64
  batch_size: 8
  data_seed: 101
  task_seed: 102
  noise_seed: 103
  data_scale: 1.0
  task_scale: 1.0
  noise_scale: 0.5
  clip: null
  use_weights: false
  distrib_name: student
  distrib_param: 3.0
  ou_step: 0.2

model:
  name: single_seq_transformer
  n_points: 64
  n_layer: 2
  n_embd: 2
  n_head: 2
  seed: 100
  use_ln: true
  use_linear_attention: false
  n_out: 2

training:
  optimizer: adam
  lr: 1.0e-4
  schedule: triangle
  warmup_steps: 10
  total_steps: 20
  clip_max_norm: 1.0

eval:
  n_samples: 16
  batch_size: 8
  data_seed: 104
  task_seed: 105
  noise_seed: 106
  every: 1
  eval_n_points: 64
  task_centers:
    - 0.
    - 0.25
    - 0.5
    - 0.75
    - 1.0
    - 1.25
    - 1.5
    - 1.75
    - 2.0
    - 2.25
    - 2.5
    - 2.75
    - 3.0
    - 3.25
    - 3.5
    - 3.75
    - 4.0

# Hydra settings
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${output_dir}/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
