dtype: float32
output_dir: ./outputs
log_level: INFO

task:
  name: noisy_linear_regression
  n_tasks: 0
  n_data: 0
  n_dims: 2
  n_points: 5
  batch_size: 8
  data_seed: 101
  task_seed: 102
  noise_seed: 103
  data_scale: 1.0
  task_scale: 1.0
  noise_scale: 0.5
  clip: 2.0
  use_weights: true

model:
  name: transformer
  n_points: 5
  n_layer: 2
  n_embd: 2
  n_head: 2
  seed: 100

training:
  optimizer: adam
  lr: 1.0e-4
  schedule: triangle
  warmup_steps: 10
  total_steps: 20

eval:
  n_samples: 16
  batch_size: 8
  data_seed: 104
  task_seed: 105
  noise_seed: 106
  every: 1
  eval_n_points: 4
  eval_ridge: true
  task_centers:
    - 2.0
    - 4.0
    - 6.0
    - 8.0

# Hydra settings
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${output_dir}/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
