dtype: float32
output_dir: ./outputs
log_level: INFO

task:
  name: noisy_linear_regression
  n_tasks: 1048576
  n_dims: 8
  n_points: 16
  batch_size: 256
  data_seed: 101
  task_seed: 102
  noise_seed: 103
  data_scale: 1.0
  task_scale: 1.0
  noise_scale: 0.5

model:
  name: transformer
  n_points: 16
  n_layer: 8
  n_embd: 128
  n_head: 2
  seed: 100

training:
  optimizer: adam
  lr: 1.0e-3
  schedule: triangle
  warmup_steps: 250000
  total_steps: 500000

eval:
  n_samples: 1048576
  batch_size: 4096
  data_seed: 104
  task_seed: 105
  noise_seed: 106
  every: 1000

# Hydra settings
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${output_dir}/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
