dtype: float32
output_dir: ./outputs
log_level: INFO

task:
  name: noisy_linear_regression
  n_tasks: 0
  n_data: 0
  n_dims: 4
  n_points: 128
  batch_size: 64
  data_seed: 101
  task_seed: 102
  noise_seed: 103
  data_scale: 1.0
  task_scale: 1.0
  noise_scale: 0.5
  clip: 1.0

model:
  name: transformer
  n_points: 128
  n_layer: 4
  n_embd: 32
  n_head: 2
  seed: 100

training:
  optimizer: adam
  lr: 1.0e-3
  schedule: warmup_cosine_decay
  warmup_steps: 5_000
  total_steps: 100_000

eval:
  n_samples: 2048
  batch_size: 64
  data_seed: 104
  task_seed: 105
  noise_seed: 106
  every: 10_000
  eval_n_points: 128
  eval_ridge: false
  task_centers:
    - 0.5
    - 1.0
    - 1.5
    - 2.0
    - 2.5
    - 3.0

# Hydra settings
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${output_dir}/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
