defaults:
  - model: gpt2_tiny
  - data: fast
  - training: fast
  - _self_

# Global settings
seed: 42
output_dir: ./outputs
log_level: INFO

# Hydra settings
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${output_dir}/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}